export const integrantes = [
    {
        id: 1,
        nombre: 'Felipe',
        area: 'Full Stack',
        imagen: 'https://acortar.link/1z86HL',
        redes: 'linkedin',
        github: 'felipe',
    },
    {
        id: 1,
        nombre: 'Maximiliano',
        area: 'Full Stack',
        imagen: 'https://acortar.link/jm2eTJ',
        redes: 'linkedin',
        github: 'maximiliano',
    },
    {
        id: 1,
        nombre: 'Camilo',
        area: 'Full Stack',
        imagen: 'https://acortar.link/meBR3y',
        redes: 'linkedin',
        github: 'camilo',
    },
    {
        id: 1,
        nombre: 'Davinson',
        area: 'Full Stack',
        imagen: 'https://acortar.link/cEBFVB',
        redes: 'linkedin',
        github: 'felipe',
    },
    {
        id: 1,
        nombre: 'Bruno',
        area: 'Full Stack',
        imagen: 'https://acortar.link/5w7eiR',
        redes: 'linkedin',
        github: 'bruno',
    },
    {
        id: 1,
        nombre: 'Marcos',
        area: 'Full Stack',
        imagen: 'https://acortar.link/QUZlC0',
        redes: 'linkedin',
        github: 'felipe',
    },
    {
        id: 1,
        nombre: 'Claudio',
        area: 'Full Stack',
        imagen: 'https://acortar.link/3dxYuS',
        redes: 'linkedin',
        github: 'felipe',
    },
    {
        id: 1,
        nombre: 'Gaston',
        area: 'Full Stack',
        imagen: 'https://acortar.link/QKqxRl',
        redes: 'linkedin',
        github: 'gaston',
    },
]