

INSERT INTO public.productos(
	nombreproducto, descproducto, precioproducto, disponibproducto, idcategoria, "createdAt", "updatedAt")
	VALUES ( 'Gafas Oculus Quest 2', 'gafas realidad virtual pro', 700000, 'completa', 2, now(), now());
INSERT INTO public.productos(
	nombreproducto, descproducto, precioproducto, disponibproducto, idcategoria, "createdAt", "updatedAt")
	VALUES ( 'Gafas Oculus Quest 1', 'gafas realidad virtual', 500000, 'completa', 2, now(), now());

INSERT INTO public.productos(
	nombreproducto, descproducto, precioproducto, disponibproducto, idcategoria, "createdAt", "updatedAt")
	VALUES ( 'TELEVISION SMART SONY S1', 'TV smart', 500000, 'completa', 2, now(), now());

INSERT INTO public.productos(
	nombreproducto, descproducto, precioproducto, disponibproducto, idcategoria, "createdAt", "updatedAt")
	VALUES ( 'SONY VAIO TROKI 1', 'gafas realidad virtual', 500000, 'completa', 2, now(), now());
